name: Maven Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -DskipTests package
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnnouncerAdvanced-1.0.0
          path: target/AnnouncerAdvanced-1.0.0.jar
